import logging
from pathlib import Path

# Importy modulov – RuntimeEngine 4.0 ich neskôr nahradí DI injekciou
from modules.fs_module import FSModule
from modules.editor_module import EditorModule

log = logging.getLogger(__name__)


class WorkflowModule:
    """
    WorkflowModule 3.5.0
    ---------------------
    Developer automation workflows for SIRIUS LOCAL AI.

    Features:
    - create project structures
    - generate module templates
    - prepare version folders
    - refactor files
    - open generated files in VS Code
    """

    def __init__(self):
        self.name = "workflow"
        self.fs = FSModule()
        self.editor = EditorModule()

    # --------------------------------------------------------
    # CREATE PROJECT STRUCTURE
    # --------------------------------------------------------
    def create_structure(self, root: str, folders: list[str]):
        root_path = Path(root).resolve()

        log.info("WORKFLOW: Creating project structure under %s", root_path)

        for folder in folders:
            full = root_path / folder
            self.fs.mkdir(str(full))

        return True

    # --------------------------------------------------------
    # GENERATE MODULE TEMPLATE
    # --------------------------------------------------------
    def generate_module(self, path: str, module_name: str):
        """
        Vytvorí nový modulový súbor s minimálnou šablónou.
        """
        target = Path(path).resolve() / f"{module_name}.py"

        template = f'''"""
{module_name}.py – generated by WorkflowModule 3.5.0
"""

class {module_name.capitalize()}:
    def __init__(self):
        self.name = "{module_name}"

    def run(self):
        pass
'''

        self.fs.write(str(target), template)
        self.editor.open_file(str(target))

        log.info("WORKFLOW: Generated module template: %s", target)
        return True

    # --------------------------------------------------------
    # PREPARE VERSION FOLDER
    # --------------------------------------------------------
    def prepare_version(self, base: str, version: str):
        """
        Vytvorí priečinok pre release verziu.
        """
        version_path = Path(base).resolve() / f"v{version}"
        self.fs.mkdir(str(version_path))

        log.info("WORKFLOW: Prepared version folder: %s", version_path)
        return True

    # --------------------------------------------------------
    # REFACTOR FILE – MOVE + OPEN
    # --------------------------------------------------------
    def refactor_move_and_open(self, src: str, dst: str):
        """
        Presunie súbor a otvorí ho vo VS Code.
        """
        if self.fs.move(src, dst):
            self.editor.open_file(dst)
            log.info("WORKFLOW: Refactored file '%s' → '%s'", src, dst)
            return True

        return False

    # --------------------------------------------------------
    # CREATE EMPTY FILE + OPEN
    # --------------------------------------------------------
    def create_and_open(self, path: str):
        """
        Vytvorí prázdny súbor a otvorí ho v editore.
        """
        self.fs.write(path, "")
        self.editor.open_file(path)

        log.info("WORKFLOW: Created and opened file: %s", path)
        return True
