import logging
from pathlib import Path

# RuntimeEngine 4.x will replace these with DI injection
from modules.fs_module import FSModule
from modules.editor_module import EditorModule

log = logging.getLogger(__name__)


class WorkflowModule:
    """
    WorkflowModule 4.5
    ---------------------
    Developer automation workflows for SIRIUS LOCAL AI.

    Updated in 4.5:
        - Deterministic Runtime4.5 behavior
        - Stable structured return values
        - Self‑Repair Layer 4.5 compatible metadata
        - Safe FS operations (FSModule 4.5)
        - Unified template generation (4.5 contract)
        - No side-effects outside FS + Editor
        - Metadata version bumped to 4.5
    """

    def __init__(self):
        self.name = "workflow"
        self.fs = FSModule()
        self.editor = EditorModule()

    # --------------------------------------------------------
    # CREATE PROJECT STRUCTURE
    # --------------------------------------------------------
    def create_structure(self, root: str, folders: list[str]):
        root_path = Path(root).resolve()
        log.info("WORKFLOW: Creating project structure under %s", root_path)

        results = []

        for folder in folders:
            full = root_path / folder
            res = self.fs.mkdir(str(full))
            results.append({
                "folder": str(full),
                "result": res
            })

        return {
            "status": "success",
            "root": str(root_path),
            "created": results,
            "workflow_version": "4.5"
        }

    # --------------------------------------------------------
    # GENERATE MODULE TEMPLATE
    # --------------------------------------------------------
    def generate_module(self, path: str, module_name: str):
        """
        Generates a new module file with a minimal template.
        Deterministic and safe.
        """
        target = Path(path).resolve() / f"{module_name}.py"

        template = f'''"""
{module_name}.py – generated by WorkflowModule 4.5
"""

class {module_name.capitalize()}:
    def __init__(self):
        self.name = "{module_name}"

    def run(self):
        pass
'''

        write_res = self.fs.write(str(target), template)
        self.editor.open_file(str(target))

        log.info("WORKFLOW: Generated module template: %s", target)

        return {
            "status": "success",
            "path": str(target),
            "write_result": write_res,
            "workflow_version": "4.5"
        }

    # --------------------------------------------------------
    # PREPARE VERSION FOLDER
    # --------------------------------------------------------
    def prepare_version(self, base: str, version: str):
        """
        Creates a folder for a release version.
        Deterministic and safe.
        """
        version_path = Path(base).resolve() / f"v{version}"
        res = self.fs.mkdir(str(version_path))

        log.info("WORKFLOW: Prepared version folder: %s", version_path)

        return {
            "status": "success",
            "version": version,
            "path": str(version_path),
            "mkdir_result": res,
            "workflow_version": "4.5"
        }

    # --------------------------------------------------------
    # REFACTOR FILE – MOVE + OPEN
    # --------------------------------------------------------
    def refactor_move_and_open(self, src: str, dst: str):
        """
        Moves a file and opens it in the editor.
        Deterministic and safe.
        """
        move_res = self.fs.move(src, dst)

        if move_res.get("status") == "success":
            self.editor.open_file(dst)
            log.info("WORKFLOW: Refactored file '%s' → '%s'", src, dst)
            return {
                "status": "success",
                "src": src,
                "dst": dst,
                "move_result": move_res,
                "workflow_version": "4.5"
            }

        return {
            "status": "error",
            "src": src,
            "dst": dst,
            "move_result": move_res,
            "workflow_version": "4.5"
        }

    # --------------------------------------------------------
    # CREATE EMPTY FILE + OPEN
    # --------------------------------------------------------
    def create_and_open(self, path: str):
        """
        Creates an empty file and opens it in the editor.
        Deterministic and safe.
        """
        write_res = self.fs.write(path, "")
        self.editor.open_file(path)

        log.info("WORKFLOW: Created and opened file: %s", path)

        return {
            "status": "success",
            "path": path,
            "write_result": write_res,
            "workflow_version": "4.5"
        }
