# Event definitions for Password Vault 4.0
# To be wired into Security Family / NL Router / Dispatcher.

PASSWORD_SAVE_EVENT = "SECURITY_EVENT_PASSWORD_SAVE"
PASSWORD_RETRIEVE_EVENT = "SECURITY_EVENT_PASSWORD_RETRIEVE"
PASSWORD_AUTOFILL_EVENT = "SECURITY_EVENT_PASSWORD_AUTOFILL"
PASSWORD_DELETE_EVENT = "SECURITY_EVENT_PASSWORD_DELETE"
PASSWORD_LIST_EVENT = "SECURITY_EVENT_PASSWORD_LIST"
PASSWORD_PHISHING_DETECTED_EVENT = "SECURITY_EVENT_PASSWORD_PHISHING_DETECTED"
