PROPOSALS_PATH = r"C:\SIRIUS_ARCHIVE\COLNIK-6.x\IPC_DATA\proposals.json"
RESPONSES_PATH = r"C:\SIRIUS_ARCHIVE\COLNIK-6.x\IPC_DATA\responses.json"
LOG_PATH = r"C:\SIRIUS_ARCHIVE\COLNIK-6.x\IPC_DATA\colnik_log.txt"
